# Use the official Python image matching the current Raspberry Pi OS (Bookworm)
FROM ros:lyrical-ros-core

# install ros package
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-demo-nodes-cpp \
    ros-${ROS_DISTRO}-demo-nodes-py && \
    rm -rf /var/lib/apt/lists/*

# Install system dependencies often needed for Pi development (GPIO, I2C, Build tools)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    python3-dev \
    pip \
    libgpiod-dev \
    liblgpio-dev \
    python3-lgpio \
    i2c-tools \
    ssh \
    sudo \
    software-properties-common \
    swig

RUN echo "source /opt/ros/lyrical/setup.bash" >> /root/.bashrc
RUN echo "source /etc/profile.d/colcon_cd.sh" >> /root/.bashrc
RUN echo "export _colcon_cd_root=/opt/ros/lyrical/" >> /root/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /root/.bashrc

RUN apt install python3-colcon-common-extensions python3-colcon-argcomplete python3-rosdep --yes
RUN rosdep init
RUN rosdep update